create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  brand_name text default 'BRAND',
  logo_url text,
  favicon_url text,
  header_button_label text default 'Contato',
  header_button_href text default '#contato',
  footer_text text,
  theme_json jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.nav_items (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null default '#',
  sort_order integer default 0,
  enabled boolean default true
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  slug text not null,
  kind text not null default 'split',
  sort_order integer default 0,
  enabled boolean default true,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;
alter table public.nav_items enable row level security;
alter table public.sections enable row level security;

insert into public.site_settings (brand_name,header_button_label,header_button_href,footer_text)
select 'urbane.studio','Agendar visita','#contato','Landing premium com CMS completo.'
where not exists (select 1 from public.site_settings);

insert into public.nav_items(label,href,sort_order,enabled)
select * from (values ('Início','#top',1,true),('Sobre','#sobre',2,true),('Serviços','#servicos',3,true),('FAQ','#faq',4,true)) as v(label,href,sort_order,enabled)
where not exists (select 1 from public.nav_items);

insert into public.sections(slug,kind,sort_order,enabled,content)
select 'top','hero',1,true,'{"image_url":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=90","eyebrow":"Premium • Curadoria • Experiência","title":"Criamos espaços e experiências que constroem valor.","text":"Uma landing page cinematográfica, limpa e inteiramente editável no CMS.","buttons":[{"label":"Conheça o projeto","href":"#sobre"},{"label":"Falar com a equipe","href":"#contato","style":"alt"}],"feature_kicker":"Destaque","feature_title":"Luxury Experience","feature_text":"Conteúdo, imagem e CTA editáveis."}'::jsonb
where not exists (select 1 from public.sections);

insert into public.sections(slug,kind,sort_order,enabled,content)
select 'sobre','cards',2,true,'{"eyebrow":"Sobre","title":"Curadoria desde o primeiro contato.","text":"Seções amplas, hierarquia clara e visual premium.","buttons":[{"label":"Saiba mais","href":"#servicos"}],"cards":[{"kicker":"01","title":"Curadoria","text":"Cards, imagens e links editáveis.","image_url":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=90","button_label":"Explorar"},{"kicker":"02","title":"Investimento","text":"CTAs e conteúdo administráveis.","image_url":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=90","button_label":"Ver mais"}]}'::jsonb
where (select count(*) from public.sections) < 2;

insert into public.sections(slug,kind,sort_order,enabled,content)
select 'faq','faq',99,true,'{"eyebrow":"FAQ","title":"Common Questions","items":[{"question":"Tudo pode ser editado?","answer":"Sim. Menus, botões, títulos, textos, imagens, áudio, ordem das seções e status de publicação."},{"question":"Posso trocar fotos e áudios?","answer":"Sim. O painel envia arquivos para o Supabase Storage e grava a URL no conteúdo."},{"question":"Funciona na Vercel?","answer":"Sim. O projeto está preparado para Next.js + Vercel e banco/Storage no Supabase."}]}'::jsonb
where not exists (select 1 from public.sections where slug='faq');

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('media','media',true,524288000,null)
on conflict (id) do update set public=true, file_size_limit=524288000;
