'use client';
import { useEffect, useState } from 'react';

const blankByKind={
 hero:{eyebrow:'Seção',title:'Novo título',text:'Novo texto',image_url:'',image_position:'center',theme:'dark',min_height:800,padding_y:80,buttons:[],feature_kicker:'',feature_title:'',feature_text:'',feature_image_url:''},
 cards:{eyebrow:'Seção',title:'Novo título',text:'Novo texto',theme:'light',min_height:760,padding_y:100,buttons:[],cards:[]},
 features:{eyebrow:'Seção',title:'Novo título',theme:'light',min_height:700,padding_y:100,milestone_kicker:'Marco',milestone_value:'100',milestone_label:'Resultado',items:[]},
 testimonials:{eyebrow:'Depoimentos',title:'Clientes',theme:'light',min_height:680,padding_y:100,items:[]},
 brandstrip:{title:'Mensagem da marca',text:'Texto',theme:'light',min_height:440,padding_y:90,words:['We','Curate','→','Impact'],button_label:'Saiba mais',button_href:'#'},
 services:{eyebrow:'Soluções',title:'Nossos serviços',theme:'light',min_height:760,padding_y:110,cards:[]},
 growth:{eyebrow:'Resultados',title:'Crescimento',text:'Texto',theme:'dark',min_height:330,padding_y:75,items:[]},
 casting:{eyebrow:'Nosso Casting',title:'Talentos que inspiram',text:'14 palestrantes.',theme:'light',min_height:980,padding_y:115,button_label:'Ver todos',button_href:'/casting',page_eyebrow:'CASTING TALKERS',page_title:'Os nomes certos.',page_text:'Texto da página de casting.',page_note:'Toque em um perfil.',end_eyebrow:'CURADORIA',end_title:'Você traz o briefing. A Talkers encontra a voz.',end_button_label:'Falar com um curador',end_button_href:'/#contato',speakers:[]},
 cta:{eyebrow:'Contato',title:'Fale com a Talkers',text:'',theme:'dark',min_height:390,padding_y:85,button_label:'Fale com a Talkers',button_href:'#contato',button_icon:'whatsapp'},
 statement:{eyebrow:'Seção',title:'Novo título',text:'Novo texto',theme:'light',min_height:650,padding_y:90},
 media:{eyebrow:'Seção',title:'Novo título',text:'Novo texto',image_url:'',video_url:'',audio_url:'',poster_url:'',video_autoplay:false,video_muted:true,audio_autoplay:false,theme:'light',min_height:760,padding_y:90,quote_kicker:'',quote_name:'',quote_text:''},
 stats:{eyebrow:'Números',title:'Resultados',theme:'light',min_height:600,padding_y:90,items:[]},
 split:{eyebrow:'Seção',title:'Novo título',text:'Novo texto',image_url:'',image_position:'center',theme:'light',min_height:760,padding_y:100,buttons:[]},
 faq:{eyebrow:'FAQ',title:'Perguntas comuns',text:'',theme:'light',min_height:650,padding_y:100,items:[]}
};
const blankSection={id:null,slug:'nova-secao',kind:'split',sort_order:50,enabled:true,content:blankByKind.split};
const sectionTypes=['hero','cards','features','testimonials','brandstrip','services','growth','casting','cta','statement','media','stats','split','faq'];

export default function AdminClient({authenticated,initialData=null,initialError=null}){
 const [auth,setAuth]=useState(authenticated),[password,setPassword]=useState(''),[data,setData]=useState(initialData),[msg,setMsg]=useState(initialError||''),[uploading,setUploading]=useState(false);
 async function login(e){e.preventDefault();setMsg('Entrando...');try{const r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password}),credentials:'same-origin'});if(r.ok){location.reload();return}setMsg('Senha inválida')}catch{setMsg('Não foi possível entrar. Tente novamente.')}}
 async function api(action,payload={}){setMsg('Salvando...');try{const r=await fetch('/api/cms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload}),credentials:'same-origin'});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Erro ao salvar');if(r.status===401)setAuth(false);return}setMsg('Salvo com sucesso');location.reload()}catch{setMsg('Erro de conexão ao salvar')}}
 async function upload(file){if(!file)return null;setUploading(true);const f=new FormData();f.append('file',file);try{const r=await fetch('/api/upload',{method:'POST',body:f});const j=await r.json();if(!r.ok){setMsg(j.error||'Erro no upload');return null}setMsg('Upload concluído');return j.url}finally{setUploading(false)}}
 if(!auth)return <div className="login"><form className="loginbox" onSubmit={login}><h1>CMS</h1><p className="small">Digite a senha do CMS.</p><F label="Senha" type="password" value={password} onChange={setPassword}/><button>Entrar</button>{msg&&<p>{msg}</p>}</form></div>;
 if(!data)return <div className="admin"><div className="panel"><h2>CMS</h2><p>{msg||'Não foi possível carregar os dados do CMS.'}</p><p className="small">O painel está ativo, mas o banco de conteúdo não respondeu. Acesse <b>/api/health</b>.</p><button onClick={()=>location.reload()}>Tentar novamente</button></div></div>;
 return <div className="admin"><div className="adminbar"><h1>CMS Talkers</h1><a href="/" target="_blank"><button className="secondary">Ver site</button></a><a href="/casting" target="_blank"><button className="secondary">Ver casting</button></a><button className="secondary" onClick={async()=>{await fetch('/api/logout',{method:'POST'});location.reload()}}>Sair</button></div>{msg&&<p className="cms-message">{msg}</p>}
  <SettingsPanel settings={data.settings||{}} save={x=>api('save_settings',{data:x})} upload={upload} uploading={uploading}/>
  <NavPanel nav={data.nav||[]} save={x=>api('save_nav',{data:x})} del={id=>api('delete_nav',{id})}/>
  <SectionsPanel sections={data.sections||[]} save={x=>api('save_section',{data:x})} del={id=>api('delete_section',{id})} upload={upload} uploading={uploading}/>
 </div>
}

function SettingsPanel({settings,save,upload,uploading}){
 const [x,setX]=useState(settings);useEffect(()=>setX(settings),[settings]);const theme=x.theme_json||{};const patchTheme=p=>setX({...x,theme_json:{...theme,...p}});
 return <div className="panel"><h2>Configurações gerais</h2><p className="small">Logo, marca, botão do topo, contatos, redes, rodapé e aparência global.</p>
  <div className="row"><F label="Nome da marca" value={x.brand_name} onChange={v=>setX({...x,brand_name:v})}/><MediaField label="Logo" value={x.logo_url} accept="image/*" upload={upload} onChange={v=>setX({...x,logo_url:v})}/><MediaField label="Favicon" value={x.favicon_url} accept="image/*" upload={upload} onChange={v=>setX({...x,favicon_url:v})}/><F label="Botão do topo" value={x.header_button_label} onChange={v=>setX({...x,header_button_label:v})}/><F label="Link do botão" value={x.header_button_href} onChange={v=>setX({...x,header_button_href:v})}/></div>
  <div className="subpanel"><h3>SEO e navegador</h3><div className="row"><F label="Título do site" value={theme.seo_title} onChange={v=>patchTheme({seo_title:v})}/><F label="Descrição do site" value={theme.seo_description} onChange={v=>patchTheme({seo_description:v})}/></div></div><div className="subpanel"><h3>Contato e redes</h3><div className="row"><F label="E-mail" value={theme.contact_email} onChange={v=>patchTheme({contact_email:v})}/><F label="Telefone" value={theme.contact_phone} onChange={v=>patchTheme({contact_phone:v})}/><F label="Cidade" value={theme.contact_city} onChange={v=>patchTheme({contact_city:v})}/><F label="WhatsApp / link" value={theme.whatsapp_url} onChange={v=>patchTheme({whatsapp_url:v})}/><F label="Instagram" value={theme.instagram_url} onChange={v=>patchTheme({instagram_url:v})}/><F label="LinkedIn" value={theme.linkedin_url} onChange={v=>patchTheme({linkedin_url:v})}/><F label="YouTube" value={theme.youtube_url} onChange={v=>patchTheme({youtube_url:v})}/></div></div>
  <div className="subpanel"><h3>Rodapé</h3><div className="row"><F label="Tagline" value={theme.footer_tagline} onChange={v=>patchTheme({footer_tagline:v})}/><F label="Título coluna 1" value={theme.footer_nav_title} onChange={v=>patchTheme({footer_nav_title:v})}/><F label="Título coluna 2" value={theme.footer_company_title} onChange={v=>patchTheme({footer_company_title:v})}/><F label="Título coluna 3" value={theme.footer_resources_title} onChange={v=>patchTheme({footer_resources_title:v})}/><F label="Título contato" value={theme.footer_contact_title} onChange={v=>patchTheme({footer_contact_title:v})}/></div><F area label="Texto institucional" value={x.footer_text} onChange={v=>setX({...x,footer_text:v})}/></div>
  <div className="subpanel"><h3>Aparência</h3><div className="row"><F label="Cor de fundo" type="color" value={theme.bg||'#f5f5f3'} onChange={v=>patchTheme({bg:v})}/><F label="Cor principal" type="color" value={theme.ink||'#0b0b0c'} onChange={v=>patchTheme({ink:v})}/><F label="Raio dos cards (px)" type="number" value={theme.radius??28} onChange={v=>patchTheme({radius:+v})}/></div></div>
  <div className="toolbar"><button onClick={()=>save(x)}>Salvar configurações</button>{uploading&&<span>Enviando...</span>}</div>
 </div>
}

function NavPanel({nav,save,del}){const [items,setItems]=useState(nav);useEffect(()=>setItems(nav),[nav]);return <div className="panel"><div className="toolbar"><h2 style={{marginRight:'auto'}}>Menus</h2><button onClick={()=>setItems([...items,{label:'Novo menu',href:'#',sort_order:99,enabled:true}])}>+ Menu</button></div>{items.map((n,i)=><div className="row itembox" key={n.id||`new${i}`}><F label="Texto do menu" value={n.label} onChange={v=>upd(setItems,items,i,{...n,label:v})}/><F label="Link" value={n.href} onChange={v=>upd(setItems,items,i,{...n,href:v})}/><F label="Ordem" type="number" value={n.sort_order} onChange={v=>upd(setItems,items,i,{...n,sort_order:+v})}/><div className="toolbar"><label><input type="checkbox" checked={n.enabled!==false} onChange={e=>upd(setItems,items,i,{...n,enabled:e.target.checked})}/> Ativo</label><button onClick={()=>save(items[i])}>Salvar</button>{n.id&&<button className="danger" onClick={()=>del(n.id)}>Excluir</button>}</div></div>)}</div>}

function SectionsPanel({sections,save,del,upload,uploading}){const [items,setItems]=useState(sections);useEffect(()=>setItems(sections),[sections]);return <div className="panel"><div className="toolbar"><h2 style={{marginRight:'auto'}}>Seções da página</h2><button onClick={()=>setItems([...items,JSON.parse(JSON.stringify(blankSection))])}>+ Nova seção</button></div><p className="small">Cada seção tem espaço próprio e todos os campos visíveis no site ficam editáveis aqui.</p><div className="sectionslist">{items.map((s,i)=><SectionEditor key={s.id||`new${i}`} item={s} onChange={v=>upd(setItems,items,i,v)} save={save} del={del} upload={upload} uploading={uploading}/>)}</div></div>}

function SectionEditor({item,onChange,save,del,upload,uploading}){
 const c=item.content||{};const setC=patch=>onChange({...item,content:{...c,...patch}});const changeKind=kind=>onChange({...item,kind,content:{...(blankByKind[kind]||blankByKind.split),...c}});
 return <details className="sectionedit" open={!item.id}><summary><b>{c.title||item.slug||'Nova seção'}</b><span>{item.kind} • ordem {item.sort_order}</span></summary>
  <div className="row topfields"><F label="Slug / âncora" value={item.slug} onChange={v=>onChange({...item,slug:v})}/><Select label="Tipo" value={item.kind} options={sectionTypes} onChange={changeKind}/><F label="Ordem" type="number" value={item.sort_order} onChange={v=>onChange({...item,sort_order:+v})}/><div className="field"><label>Status</label><label className="check"><input type="checkbox" checked={item.enabled!==false} onChange={e=>onChange({...item,enabled:e.target.checked})}/> Publicada</label></div></div>
  <CommonFields c={c} setC={setC}/>
  {(item.kind==='hero'||item.kind==='split'||item.kind==='cards'||item.kind==='media')&&<MediaSpecific kind={item.kind} c={c} setC={setC} upload={upload}/>} 
  {(item.kind==='hero'||item.kind==='split'||item.kind==='cards')&&<ButtonsEditor items={c.buttons||[]} onChange={buttons=>setC({buttons})}/>} 
  {item.kind==='hero'&&<HeroFeatureEditor c={c} setC={setC} upload={upload}/>} 
  {item.kind==='cards'&&<CardsEditor items={c.cards||[]} onChange={cards=>setC({cards})} upload={upload}/>} 
  {item.kind==='features'&&<FeaturesEditor c={c} setC={setC}/>} 
  {item.kind==='testimonials'&&<TestimonialsEditor items={c.items||[]} onChange={items=>setC({items})} upload={upload}/>} 
  {item.kind==='brandstrip'&&<BrandStripEditor c={c} setC={setC}/>} 
  {item.kind==='services'&&<ServiceCardsEditor items={c.cards||[]} onChange={cards=>setC({cards})} upload={upload}/>} 
  {item.kind==='growth'&&<StatsEditor items={c.items||[]} onChange={items=>setC({items})}/>} 
  {item.kind==='casting'&&<CastingEditor c={c} setC={setC} upload={upload}/>} 
  {item.kind==='cta'&&<CtaEditor c={c} setC={setC}/>} 
  {item.kind==='media'&&<QuoteEditor c={c} setC={setC}/>} 
  {item.kind==='stats'&&<StatsEditor items={c.items||[]} onChange={items=>setC({items})}/>} 
  {item.kind==='faq'&&<FaqEditor items={c.items||[]} onChange={items=>setC({items})}/>} 
  <div className="toolbar savebar"><button onClick={()=>save(item)}>Salvar seção</button>{item.id&&<button className="danger" onClick={()=>del(item.id)}>Excluir seção</button>}{uploading&&<span>Enviando mídia...</span>}</div>
 </details>
}

function CommonFields({c,setC}){return <div className="subpanel"><h3>Conteúdo e espaço</h3><div className="row"><F label="Etiqueta / eyebrow" value={c.eyebrow} onChange={v=>setC({eyebrow:v})}/><Select label="Tema" value={c.theme||'light'} options={['light','dark']} onChange={v=>setC({theme:v})}/><F label="Altura mínima desktop (px)" type="number" value={c.min_height??720} onChange={v=>setC({min_height:+v})}/><F label="Espaço vertical (px)" type="number" value={c.padding_y??96} onChange={v=>setC({padding_y:+v})}/><F label="Cor de fundo opcional" type="color" value={c.background_color||'#f5f5f3'} onChange={v=>setC({background_color:v})}/><F label="Cor do texto opcional" type="color" value={c.text_color||'#0b0b0b'} onChange={v=>setC({text_color:v})}/></div><F label="Título" value={c.title} onChange={v=>setC({title:v})}/><F area label="Texto / descrição" value={c.text} onChange={v=>setC({text:v})}/></div>}
function MediaSpecific({kind,c,setC,upload}){return <div className="subpanel"><h3>Mídia</h3><div className="row"><MediaField label="Imagem principal" value={c.image_url} accept="image/*" upload={upload} onChange={v=>setC({image_url:v})}/><Select label="Posição da imagem" value={c.image_position||'center'} options={['center','top','bottom','left','right']} onChange={v=>setC({image_position:v})}/>{kind==='media'&&<><MediaField label="Vídeo" value={c.video_url} accept="video/*" upload={upload} onChange={v=>setC({video_url:v})}/><MediaField label="Áudio" value={c.audio_url} accept="audio/*" upload={upload} onChange={v=>setC({audio_url:v})}/><MediaField label="Poster do vídeo" value={c.poster_url} accept="image/*" upload={upload} onChange={v=>setC({poster_url:v})}/></>}</div></div>}
function HeroFeatureEditor({c,setC,upload}){return <div className="subpanel"><h3>Card de destaque da Hero</h3><div className="row"><MediaField label="Imagem do card" value={c.feature_image_url} accept="image/*" upload={upload} onChange={v=>setC({feature_image_url:v})}/><F label="Etiqueta" value={c.feature_kicker} onChange={v=>setC({feature_kicker:v})}/><F label="Título" value={c.feature_title} onChange={v=>setC({feature_title:v})}/></div><F area label="Texto" value={c.feature_text} onChange={v=>setC({feature_text:v})}/></div>}
function FeaturesEditor({c,setC}){return <><div className="subpanel"><h3>Marco / contador</h3><div className="row"><F label="Etiqueta" value={c.milestone_kicker} onChange={v=>setC({milestone_kicker:v})}/><F label="Número" value={c.milestone_value} onChange={v=>setC({milestone_value:v})}/><F label="Descrição" value={c.milestone_label} onChange={v=>setC({milestone_label:v})}/></div></div><Repeater title="Benefícios" addLabel="+ Benefício" onAdd={()=>setC({items:[...(c.items||[]),{icon:'spark',title:'Novo benefício',text:'Descrição'}]})}>{(c.items||[]).map((x,i)=><div className="itembox" key={i}><div className="row"><Select label="Ícone" value={x.icon||'spark'} options={['target','spark','phone','people','check']} onChange={v=>arrPatch(c.items,set=>setC({items:set}),i,{...x,icon:v})}/><F label="Título" value={x.title} onChange={v=>arrPatch(c.items,set=>setC({items:set}),i,{...x,title:v})}/></div><F area label="Texto" value={x.text} onChange={v=>arrPatch(c.items,set=>setC({items:set}),i,{...x,text:v})}/><ItemActions i={i} items={c.items||[]} onChange={items=>setC({items})}/></div>)}</Repeater></>}
function TestimonialsEditor({items,onChange,upload}){return <Repeater title="Depoimentos" addLabel="+ Depoimento" onAdd={()=>onChange([...items,{rating:'★★★★★',quote:'Novo depoimento',name:'Nome',role:'Cargo',image_url:'',featured:false}])}>{items.map((x,i)=><div className="itembox" key={i}><div className="row"><F label="Estrelas" value={x.rating} onChange={v=>arrPatch(items,onChange,i,{...x,rating:v})}/><F label="Nome" value={x.name} onChange={v=>arrPatch(items,onChange,i,{...x,name:v})}/><F label="Cargo" value={x.role} onChange={v=>arrPatch(items,onChange,i,{...x,role:v})}/><MediaField label="Foto" value={x.image_url} accept="image/*" upload={upload} onChange={v=>arrPatch(items,onChange,i,{...x,image_url:v})}/><label className="check"><input type="checkbox" checked={!!x.featured} onChange={e=>arrPatch(items,onChange,i,{...x,featured:e.target.checked})}/> Destaque escuro</label></div><F area label="Depoimento" value={x.quote} onChange={v=>arrPatch(items,onChange,i,{...x,quote:v})}/><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function BrandStripEditor({c,setC}){const words=c.words||['We','Curate','→','Impact'];return <div className="subpanel"><h3>Faixa de marca</h3><div className="row">{[0,1,2,3].map(i=><F key={i} label={`Palavra ${i+1}`} value={words[i]} onChange={v=>{const a=[...words];a[i]=v;setC({words:a})}}/>)}<F label="Legenda das redes" value={c.social_label} onChange={v=>setC({social_label:v})}/><F label="Texto do botão" value={c.button_label} onChange={v=>setC({button_label:v})}/><F label="Link do botão" value={c.button_href} onChange={v=>setC({button_href:v})}/></div></div>}
function ServiceCardsEditor({items,onChange,upload}){return <Repeater title="Cards de soluções" addLabel="+ Solução" onAdd={()=>onChange([...items,{kicker:'CATEGORIA',title:'Nova solução',text:'Descrição',image_url:''}])}>{items.map((x,i)=><div className="itembox" key={i}><div className="row"><F label="Categoria" value={x.kicker} onChange={v=>arrPatch(items,onChange,i,{...x,kicker:v})}/><F label="Título" value={x.title} onChange={v=>arrPatch(items,onChange,i,{...x,title:v})}/><MediaField label="Imagem" value={x.image_url} accept="image/*" upload={upload} onChange={v=>arrPatch(items,onChange,i,{...x,image_url:v})}/></div><F area label="Texto" value={x.text} onChange={v=>arrPatch(items,onChange,i,{...x,text:v})}/><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function CastingEditor({c,setC,upload}){return <><div className="subpanel"><h3>Botão e página completa do Casting</h3><div className="row"><F label="Botão na home" value={c.button_label} onChange={v=>setC({button_label:v})}/><F label="Link do botão" value={c.button_href} onChange={v=>setC({button_href:v})}/><F label="Etiqueta página Casting" value={c.page_eyebrow} onChange={v=>setC({page_eyebrow:v})}/><F label="Título página Casting" value={c.page_title} onChange={v=>setC({page_title:v})}/><F label="Nota página Casting" value={c.page_note} onChange={v=>setC({page_note:v})}/></div><F area label="Texto página Casting" value={c.page_text} onChange={v=>setC({page_text:v})}/><div className="row"><F label="Etiqueta CTA final" value={c.end_eyebrow} onChange={v=>setC({end_eyebrow:v})}/><F label="Título CTA final" value={c.end_title} onChange={v=>setC({end_title:v})}/><F label="Botão CTA final" value={c.end_button_label} onChange={v=>setC({end_button_label:v})}/><F label="Link CTA final" value={c.end_button_href} onChange={v=>setC({end_button_href:v})}/></div></div><SpeakersEditor items={c.speakers||[]} onChange={speakers=>setC({speakers})} upload={upload}/></>}
function SpeakersEditor({items,onChange,upload}){return <Repeater title="Palestrantes" addLabel="+ Palestrante" onAdd={()=>onChange([...items,{name:'Novo palestrante',category:'Tema',role:'Especialista',short:'Descrição curta',bio:'Biografia',image_url:'',tags:['Curadoria'],href:'#contato'}])}>{items.map((x,i)=><div className="itembox speaker-edit" key={i}><div className="row"><F label="Nome" value={x.name} onChange={v=>arrPatch(items,onChange,i,{...x,name:v})}/><F label="Categoria" value={x.category} onChange={v=>arrPatch(items,onChange,i,{...x,category:v})}/><F label="Cargo / posição" value={x.role} onChange={v=>arrPatch(items,onChange,i,{...x,role:v})}/><MediaField label="Foto" value={x.image_url} accept="image/*" upload={upload} onChange={v=>arrPatch(items,onChange,i,{...x,image_url:v})}/><F label="Link / disponibilidade" value={x.href} onChange={v=>arrPatch(items,onChange,i,{...x,href:v})}/></div><F area label="Descrição curta" value={x.short} onChange={v=>arrPatch(items,onChange,i,{...x,short:v})}/><F area label="Biografia" value={x.bio} onChange={v=>arrPatch(items,onChange,i,{...x,bio:v})}/><F label="Tags (separadas por vírgula)" value={(x.tags||[]).join(', ')} onChange={v=>arrPatch(items,onChange,i,{...x,tags:v.split(',').map(t=>t.trim()).filter(Boolean)})}/><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function CtaEditor({c,setC}){return <div className="subpanel"><h3>Botão da chamada final</h3><div className="row"><F label="Texto do botão" value={c.button_label} onChange={v=>setC({button_label:v})}/><F label="Link do botão" value={c.button_href} onChange={v=>setC({button_href:v})}/><Select label="Ícone" value={c.button_icon||'arrow'} options={['arrow','whatsapp']} onChange={v=>setC({button_icon:v})}/></div></div>}
function ButtonsEditor({items,onChange}){return <Repeater title="Botões" addLabel="+ Botão" onAdd={()=>onChange([...items,{label:'Novo botão',href:'#',style:'default'}])}>{items.map((b,i)=><div className="itembox" key={i}><div className="row"><F label="Texto" value={b.label} onChange={v=>arrPatch(items,onChange,i,{...b,label:v})}/><F label="Link" value={b.href} onChange={v=>arrPatch(items,onChange,i,{...b,href:v})}/><Select label="Estilo" value={b.style||'default'} options={['default','alt']} onChange={v=>arrPatch(items,onChange,i,{...b,style:v})}/></div><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function CardsEditor({items,onChange,upload}){return <Repeater title="Cards" addLabel="+ Card" onAdd={()=>onChange([...items,{kicker:'',title:'Novo card',text:'',image_url:'',button_label:'Saiba mais',button_href:'#'}])}>{items.map((x,i)=><div className="itembox" key={i}><div className="row"><F label="Kicker" value={x.kicker} onChange={v=>arrPatch(items,onChange,i,{...x,kicker:v})}/><F label="Título" value={x.title} onChange={v=>arrPatch(items,onChange,i,{...x,title:v})}/><MediaField label="Imagem" value={x.image_url} accept="image/*" upload={upload} onChange={v=>arrPatch(items,onChange,i,{...x,image_url:v})}/><F label="Texto do botão" value={x.button_label} onChange={v=>arrPatch(items,onChange,i,{...x,button_label:v})}/><F label="Link do botão" value={x.button_href} onChange={v=>arrPatch(items,onChange,i,{...x,button_href:v})}/></div><F area label="Texto" value={x.text} onChange={v=>arrPatch(items,onChange,i,{...x,text:v})}/><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function QuoteEditor({c,setC}){return <div className="subpanel"><h3>Depoimento / card lateral</h3><div className="row"><F label="Etiqueta" value={c.quote_kicker} onChange={v=>setC({quote_kicker:v})}/><F label="Nome" value={c.quote_name} onChange={v=>setC({quote_name:v})}/></div><F area label="Texto" value={c.quote_text} onChange={v=>setC({quote_text:v})}/></div>}
function StatsEditor({items,onChange}){return <Repeater title="Números / indicadores" addLabel="+ Indicador" onAdd={()=>onChange([...items,{text:'Descrição',value:'0+'}])}>{items.map((x,i)=><div className="itembox" key={i}><div className="row"><F label="Descrição" value={x.text} onChange={v=>arrPatch(items,onChange,i,{...x,text:v})}/><F label="Número / valor" value={x.value} onChange={v=>arrPatch(items,onChange,i,{...x,value:v})}/></div><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function FaqEditor({items,onChange}){return <Repeater title="Perguntas e respostas" addLabel="+ Pergunta" onAdd={()=>onChange([...items,{question:'Nova pergunta',answer:'Nova resposta'}])}>{items.map((x,i)=><div className="itembox" key={i}><F label="Pergunta" value={x.question} onChange={v=>arrPatch(items,onChange,i,{...x,question:v})}/><F area label="Resposta" value={x.answer} onChange={v=>arrPatch(items,onChange,i,{...x,answer:v})}/><ItemActions i={i} items={items} onChange={onChange}/></div>)}</Repeater>}
function Repeater({title,addLabel,onAdd,children}){return <div className="subpanel"><div className="toolbar"><h3 style={{marginRight:'auto'}}>{title}</h3><button className="secondary" onClick={onAdd}>{addLabel}</button></div>{children}</div>}
function ItemActions({i,items,onChange}){return <div className="toolbar"><button className="secondary" disabled={i===0} onClick={()=>move(items,onChange,i,-1)}>↑</button><button className="secondary" disabled={i===items.length-1} onClick={()=>move(items,onChange,i,1)}>↓</button><button className="danger" onClick={()=>onChange(items.filter((_,j)=>j!==i))}>Remover</button></div>}
function MediaField({label,value='',accept,upload,onChange}){return <div className="field"><label>{label}</label><input value={value||''} placeholder="URL ou envie um arquivo" onChange={e=>onChange(e.target.value)}/><input className="fileinput" type="file" accept={accept} onChange={async e=>{const u=await upload(e.target.files?.[0]);if(u)onChange(u)}}/></div>}
function Select({label,value,options,onChange}){return <div className="field"><label>{label}</label><select value={value||options[0]} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></div>}
function F({label,value='',onChange,area=false,type='text'}){return <div className="field"><label>{label}</label>{area?<textarea value={value||''} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</div>}
function upd(setter,items,i,value){const a=[...items];a[i]=value;setter(a)}
function arrPatch(items,onChange,i,value){const a=[...(items||[])];a[i]=value;onChange(a)}
function move(items,onChange,i,dir){const j=i+dir;if(j<0||j>=items.length)return;const a=[...items];[a[i],a[j]]=[a[j],a[i]];onChange(a)}
